-- Lets the telegram-bot function run an arbitrary SELECT (generated by an LLM from a
-- plain-English question) without ever giving it write access. Defense in depth:
--   1. The LLM is instructed to only ever write a SELECT.
--   2. The Edge Function re-checks the SQL text before calling this function.
--   3. This function itself rejects anything that isn't a SELECT, wraps it so it can
--      only ever read (not execute DML/DDL hidden inside, since it's nested as a
--      read-only subquery), and is only callable by the service role — anon and
--      authenticated clients are explicitly denied.
create or replace function public.run_readonly_query(query text)
returns jsonb
language plpgsql
security definer
set statement_timeout = '5s'
as $$
declare
  result jsonb;
begin
  if query !~* '^\s*select\b' then
    raise exception 'Only SELECT statements are allowed';
  end if;
  if query ~* '\b(insert|update|delete|drop|alter|truncate|grant|revoke|create)\b' then
    raise exception 'Query contains a disallowed keyword';
  end if;

  execute format('select coalesce(jsonb_agg(t), ''[]''::jsonb) from (%s) t', query) into result;
  return result;
end;
$$;

revoke all on function public.run_readonly_query(text) from public, anon, authenticated;
grant execute on function public.run_readonly_query(text) to service_role;
